"""empty message

Revision ID: 0022e936988a
Revises: 91477e2a1fe5
Create Date: 2024-08-01 00:39:09.941966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0022e936988a'
down_revision = '91477e2a1fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('qty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
