"""empty message

Revision ID: 0a64e90a6aba
Revises: 8af99a7ebab6
Create Date: 2024-08-25 01:14:09.803734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a64e90a6aba'
down_revision = '8af99a7ebab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_ibfk_1', 'menu', ['menu_id'], ['menu_id'])

    # ### end Alembic commands ###
