"""empty message

Revision ID: 23359e497b50
Revises: 5f2b8529461b
Create Date: 2024-07-11 13:06:58.425596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23359e497b50'
down_revision = '5f2b8529461b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['menu_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('menu_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
