"""empty message

Revision ID: 4fe8da89510c
Revises: a8247224caaf
Create Date: 2024-08-04 12:13:08.748737

"""
from sqlalchemy import Text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fe8da89510c'
down_revision = 'a8247224caaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', postgresql.JSON(astext_type=Text()), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['order_id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['menu_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('menu_id')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('items')

    # ### end Alembic commands ###
