"""empty message

Revision ID: 5f2b8529461b
Revises: 0333fdf9dd78
Create Date: 2024-07-11 12:54:07.132989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f2b8529461b'
down_revision = '0333fdf9dd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.drop_column('menu_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_ibfk_1', 'menu', ['menu_id'], ['menu_id'])

    # ### end Alembic commands ###
