"""empty message

Revision ID: 65341578f320
Revises: 0022e936988a
Create Date: 2024-08-01 00:42:39.782727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65341578f320'
down_revision = '0022e936988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', postgresql.JSON(astext_type=Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('items')

    # ### end Alembic commands ###
