"""empty message

Revision ID: 76b3163b1600
Revises: e6eeef5a8ed6
Create Date: 2024-07-31 14:48:41.815482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b3163b1600'
down_revision = 'e6eeef5a8ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_price')
        batch_op.drop_column('qty')

    # ### end Alembic commands ###
