"""empty message

Revision ID: 91477e2a1fe5
Revises: 664efb69e4c3
Create Date: 2024-07-31 23:40:13.922741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91477e2a1fe5'
down_revision = '664efb69e4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_qty', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('total_qty')

    # ### end Alembic commands ###
