"""empty message

Revision ID: 938cf7333b88
Revises: 23359e497b50
Create Date: 2024-07-13 21:03:08.772449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938cf7333b88'
down_revision = '23359e497b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
