"""empty message

Revision ID: a8247224caaf
Revises: 65341578f320
Create Date: 2024-08-04 12:11:11.190930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8247224caaf'
down_revision = '65341578f320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_constraint('commands_ibfk_1', type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_ibfk_1', 'menu', ['menu_id'], ['menu_id'])

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('commands_ibfk_1', 'order', ['order_id'], ['order_id'])

    # ### end Alembic commands ###
