"""empty message

Revision ID: ce49528184e5
Revises: ee548d865f18
Create Date: 2024-09-16 15:19:30.898743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce49528184e5'
down_revision = 'ee548d865f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['order_id'])

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', mysql.TEXT(), nullable=False))
        batch_op.alter_column('img',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
