"""empty message

Revision ID: d305009effeb
Revises: ce49528184e5
Create Date: 2024-09-16 16:03:40.194714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd305009effeb'
down_revision = 'ce49528184e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', mysql.TEXT(), nullable=False))
        batch_op.alter_column('img',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
