"""empty message

Revision ID: e6eeef5a8ed6
Revises: 1d760c8589c7
Create Date: 2024-07-19 22:11:45.202122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6eeef5a8ed6'
down_revision = '1d760c8589c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['menu_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
