"""empty message

Revision ID: ee548d865f18
Revises: 858d823b35f4
Create Date: 2024-09-16 14:24:41.976705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee548d865f18'
down_revision = '858d823b35f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_constraint('commands_ibfk_1', type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=50), nullable=False))
        batch_op.alter_column('img',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.drop_column('filename')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('commands_ibfk_1', 'order', ['order_id'], ['order_id'])

    # ### end Alembic commands ###
