"""empty message

Revision ID: fef8691bb418
Revises: 0a64e90a6aba
Create Date: 2024-08-25 01:21:31.356399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fef8691bb418'
down_revision = '0a64e90a6aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_constraint('commands_ibfk_1', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('commands_ibfk_1', 'order', ['order_id'], ['order_id'])

    # ### end Alembic commands ###
